- name: Perform tests
  hosts: all
  gather_facts: True
  vars:
    fetch_directory: "{{ playbook_dir }}/fetch"
    script_path: "perf3_script.py"
  tasks:
    - name: Set facts
      set_fact:
        output_directory: "{{ ansible_env.HOME }}/iperf3_tests"
      # host: "{{ host }}"

    - name: Create output directory in remote nodes
      file:
        path: "{{ output_directory }}"
        state: directory

    - name: Change wmem_max and rmem_max
      become: True
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
      with_items:
        - { name: net.core.rmem_max, value: 2147483647 }
        - { name: net.core.wmem_max, value: 2147483647 }

    - name: Start iperf3 servers
      command: "iperf3 --server --daemon"

    #Simulate serial, one client at a time
    - include_tasks: clients.yml
      with_items: "{{ ansible_play_batch }}"
      when: "hostvars[host_item].inventory_hostname == inventory_hostname"
      loop_control:
        loop_var: host_item
      tags: [run_tests]

    - name: Kill servers
      command: "pkill iperf3"
    
    - name: Register result files
      find:
        paths: "{{ output_directory }}"
        patterns: "{{ ansible_ssh_host }}*"
        file_type: file
      register: find_results

    - name: Create directory on local host for fetching result files (make sure it's empty)
      run_once: True
      local_action:
        module: file
        args:
          path: "{{ fetch_directory }}"
          state: "{{ item }}"
      with_items:
        - absent
        - directory

    - name: Fetch result files
      fetch:
        src: "{{ item.path }}"
        dest: "{{ fetch_directory }}/"
        flat: True
      with_items: "{{ find_results.files }}"

    - name: Template script
      run_once: True
      local_action:
        module: template
        args:
          src: "{{ playbook_dir }}/{{ script_path }}.j2"
          dest: "{{ playbook_dir }}/{{ script_path }}"
      tags: template

    - name: Run python script
      run_once: True
      local_action:
        module: "shell python {{ script_path }}"
        args:
          chdir: "{{ playbook_dir }}"
      register: script_results

    - name: Print dataframe
      run_once: True
      debug:
        var: script_results.stdout_lines
